### ISSUE TITLE
.storage renewal contract

### ISSUE THREAD

**Issue by jennijuju** [lotus-web3/dotStorage-deal-renewal#1]
https://nft.storage is planning to deploy a client contract upon FEVM launch day to renew the past deals they have made that are about to expire. A couple of product requirements specific to their use cases that requires changes in the base client contract:
- [x] start epoch, duration (~500), price (will be zero), verified (true), client collateral and SP collateral(0),  will be hardcoded in the contract for all the deal proposals
- [x] have a whitelist for SPs who can make deal with this contract (set upon deployment?)
- [x] AddSPs
- [x] RemoveSPs
- [x] AuthenticateMessage should do proposal validation against the hard-coded proposal schema.
- [x] Remove market escrow functionalities (add balance , withdraw balance)
- [x] each piece can only bee claimed once, by one SP - first come first serve
- [x] contract should be non payable.
- [ ] ~Nice to have: be able to extend the verified piece to be stored for 5 years by adding [extendClaimTerms](https://github.com/Zondax/filecoin-solidity/blob/master/contracts/v0.8/VerifRegAPI.sol#L65)~
------- Note --------
- Requirements list can be found [here](https://www.notion.so/ecosystem-wg/Auto-renew-NFT-Storage-deals-via-FEVM-smart-contracts-Overview-Product-Requirements-432791108a914a95bb2ed0ea34a7c678?pvs=4#76ec99470cc14be2a9cc0ad0a794d47d)
- This project is for demonstrative purposes.
- It is possible that the contract needs to be redeployed if the flaws were detected after launch.
- The contract is meant to be operational for a certain period, not a long-term production operation.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/42981373/222873597-d91e0715-8b33-41c9-b350-779deff3ba98.png">

**Comment by elizabeth-griffiths** [comment]
@jennijuju let's remove the requirement: 
`Nice to have: be able to extend the verified piece to be stored for 5 years by adding [extendClaimTerms](https://github.com/Zondax/filecoin-solidity/blob/master/contracts/v0.8/VerifRegAPI.sol#L65)`

So that I have certainty around how long the deals will be renewed and can confidently say the time period in comms
