### ISSUE TITLE
Launch Day Operation Runbook

### ISSUE THREAD

**Issue by jennijuju** [lotus-web3/dotStorage-deal-renewal#12]
Launch day operation book can be found [here](https://docs.google.com/document/d/1ZYWw2TcJuql1xFeCdXfr_idHI_pyDpA-fnlVy_jcm20/edit?usp=sharing)

Create the runbook for the launch day operation, including the war room setup, who should be there, the steps/instructions to take, and so on. 

All parties involved in #9 should ack this runbook and their part by EOW, and all tooling needed should be ready, tested and has instruction by EOW as well.

**Comment by elizabeth-griffiths** [comment]
Noting that today in standup we agreed @elizabeth-griffiths will help with marketing part of runbook

**Comment by elizabeth-griffiths** [comment]
And also that we agreed launch will be at 3pm EST (7am Sydney time)

**Comment by elizabeth-griffiths** [comment]
Daylight savings time kicks in, so correction:  3pm EST (6am Sydney time)
I'm working on the marketing part of the runbook today, will need input from marketing tomorrow before I can finish it.
