### ISSUE TITLE
Toolings/scripts for contract operation  

### ISSUE THREAD

**Issue by jennijuju** [lotus-web3/dotStorage-deal-renewal#2]
We need a set of tooling for interacting with contracts. 
- [x] @snissn contract deployment
- [x] @snissn Add SP/Remove SP
- [x] @snissn taking the data information for the deal proposals  from a json/csv and creating deal proposals 
- [x] @snissn batch/fast csv -> deal proposals a69030657605090420d203fa3b92fea87ee439d0

**Comment by snissn** [comment]
We want to have an allow list of SPs and be able to manage that allow list.

Can I have clarity on how that will be structured? IE there's a struct:

```
struct ProviderSet {
    bytes provider;
    bool valid;
}
```

will the SPs be specified by `bytes provider` ? 

It's fine in the contract if they're just a bytes blob

**Comment by jennijuju** [comment]
We will be getting the storage miner actor IDs (that's whats in deal proposal) and I think the type would be the same with https://github.com/Zondax/filecoin-solidity/blob/efdb3fa4b20bdcfa6e9648b77b7a221fa24aa68c/contracts/v0.8/types/CommonTypes.sol#L73. wydt?

cc @shrenujbansal to confirm

**Comment by snissn** [comment]
i like actor ids! 🤣

**Comment by snissn** [comment]
I need an actual example of bytes provider here to ensure I can extract a uint64 actor id out of it :)

**Comment by jennijuju** [comment]
> taking the data information for the deal proposals from a json/csv and creating deal proposals

Sample data file
https://github.com/lotus-web3/dotStorage-deal-renewal/pull/13/files

**Comment by jennijuju** [comment]
https://github.com/lotus-web3/dotStorage-deal-renewal/blob/main/scripts/renew.py
