### ISSUE TITLE
Storage Provider preparation

### ISSUE THREAD

**Issue by jennijuju** [lotus-web3/dotStorage-deal-renewal#6]
- [x] @brendalee @tippyflitsuk SP outreach
  - [x] @brendalee @elizabeth-griffiths to prepare SP out reach comm with a summary, requirement and signup forms. 
  - [x] @brendalee @elizabeth-griffiths to share the requirements and signup form at SPWG call
  - [x] @tippyflitsuk has been collecting willing SPs [here](https://www.notion.so/pl-strflt/Participating-Deal-Contract-SPs-95ba53012e1642ab98ea8d4ffcae6fe8)
 - [x] @brendalee to vet SPs and create list
- [x] @brendalee upload pre-vetted SP list that will claim deals from this contract, including their miner actor IDs and slack handles, whether they will be testing on hyperspace, and when they can start to accept deals on mainnet.

**Comment by brendalee** [comment]
thanks @jennijuju - quick update on this as of 3/6/2023
- @elizabeth-griffiths has a presentation ready that we can share with SPs, and we are presenting in various SPWG today
- we have a google form for signup to collect SP information

Will follow up this week on the last one based on SP signups

**Comment by elizabeth-griffiths** [comment]
I recorded a short 2.45 min video for EMEA and anyone from NA who missed it. Here it is: https://www.loom.com/share/7dfb9b533a1f42a29a6feee453a4e8cc
You can also share out the form directly here: http://bit.ly/3ZKoL5u

**Comment by elizabeth-griffiths** [comment]
I'm unable to tag tippyflits for some reason....
@brendalee do you happen to know if the list he's connecting (referenced above) is for this project in particular?

**Comment by brendalee** [comment]
@elizabeth-griffiths I don't think it's specific to this project, but we could leverage those SPs for this project too :) (cc @TippyFlitsUK)

**Comment by TippyFlitsUK** [comment]
I can't imagine there would be any problem with that at all. We're ready to rock wherever you need us. 🚀

**Comment by elizabeth-griffiths** [comment]
I have done the following:

- confirmed (via the form) that SPs who signed up qualify.
- confirmed with @brendalee that we don't need to do further vetting
- [created spreadsheet here ](https://docs.google.com/spreadsheets/d/1YcCMdK4KRN_OrDGhmEDLEHzD6I7SLzDNP15OKg3L4Mc/edit#gid=0)with their miner actor IDs and slack handles, whether they will be testing on hyperspace, and when they can start to accept deals on mainnet.
- In the draft comms to SPs, I'm encouraging them to start accepting deals early (14th/15th) and emphasizing first come first served. 

@jennijuju based on this, I think all of the tasks outlined for this issue can be marked as done.

**Comment by elizabeth-griffiths** [comment]
Confirming I have messaged SPs who had more than one miner ID, and will update the whitelist if I hear that any of the minerIDs will not be active.

**Comment by brendalee** [comment]
closing this issue now! :) thanks all for partnering together on this!
