### ISSUE TITLE
e2e testing on hyperspace 

### ISSUE THREAD

**Issue by jennijuju** [lotus-web3/dotStorage-deal-renewal#8]
- [x]  Deploy the contract on hyperspace  @shrenujbansal 
- [x]  Allocate Datacap @jennijuju 
- [x]  Create Deal proposals  @shrenujbansal 
- [x] internal Lotus SP testing @reiers, @TippyFlitsUK
- [x]  Vetted SP deal making Testing @brendalee
- [ ] Test run deploy contract on @elizabeth-griffiths computer with @shrenujbansal

**Comment by elizabeth-griffiths** [comment]
@shrenujbansal let's schedule the test run. Does your Monday work?

**Comment by jennijuju** [comment]
> @shrenujbansal let's schedule the test run. Does your Monday work?

Testing on Monday is risky - if we found anything wrong it will directly lead to missing the desired launch day. I would recommend Thursday - no later than this Friday.

**Comment by elizabeth-griffiths** [comment]
Needs to be your Thursday then. Your Friday is my Saturday :)
What do I need to do in order to prepare for testing? 
* Create wallet
* Anything else?

**Comment by elizabeth-griffiths** [comment]
@shrenujbansal @jennijuju following up on when we will test and if there's anything else you need me to do to prepare?

**Comment by elizabeth-griffiths** [comment]
FYI @brendalee @shrenujbansal @jennijuju :

Wallet for testing:
- Confirming that I have created the wallet.
- I do not have testnet FIL. If we need that please send to the FIL address: f1ptuhokomj6n5gttyusxgytlpzt2u6gkck6qvo4i

SP whitelist for testing:
- I'm assuming we're also testing the whitelist functionality, and that you need the list of SPs for testing.[ Here is the list. ](https://docs.google.com/spreadsheets/d/1YcCMdK4KRN_OrDGhmEDLEHzD6I7SLzDNP15OKg3L4Mc/edit?usp=sharing)Note there is one SP who is on this list that **may **not**** meet criteria (Meest NAM). I am reaching out to them and will let you know if we need to remove them

SP attendance at synchronous testing
- Note that in the sign-up form, @ Nathan Dragun and @json said that they will not be testing on hyperspace. 
- In addition, a few SPs said they will not accept deals in mainnet until various dates on and after 3/20. I will highlight to these SPs that they should reconsider timing. It would be great if you can reiterate this at the testing. Those SPs are: @Meest Nam, Nathanial Marsh, @ Nathan Dragun
- I have requested from the SPs that if they are not able to attend the synchronous testing, they should reach out to the team in #deal-client-contract.
- @brendalee, I have noted that @ tippyflits, Nicholas, Nicklas, and phil collins (PL infrastructure) are PL affiliated. I don't see Nicholas or Phil Collins signed up. Can you please let me know which entry is theirs (list linked above) and if there are any other PL affiliated SPs signed up?

**Comment by brendalee** [comment]
@elizabeth-griffiths there is no Nicholas. Unfortunately filcollins won’t be joining the testing this time. Did you see a signup or not yet? If not yet, I will get you the minerID for filcollins

**Comment by brendalee** [comment]
@elizabeth-griffiths filcollins minerID : f01953925
